node:
  build: .
  ports:
    - "3000:3000"
  links:
    - database
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
  restart: always

database:
  image: postgres:9.4
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  restart: always