branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
global:
  application_name: node-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.7.1
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
